apiVersion: apps/v1
kind: Deployment
metadata:
  name: delivery-service
  namespace: food-delivery-system
  labels:
    app: delivery-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: delivery-service
  template:
    metadata:
      labels:
        app: delivery-service
    spec:
      containers:
        - name: delivery-service
          image: delivery-service:latest
          ports:
            - containerPort: 5004
          env:
            - name: PORT
              value: "5004"
            - name: MONGO_URL
              valueFrom:
                configMapKeyRef:
                  name: mongodb-config
                  key: delivery-service-mongodb-url
          resources:
            limits:
              cpu: "0.5"
              memory: "512Mi"
            requests:
              cpu: "0.2"
              memory: "256Mi"
