#version: "3.8"
services:
  user-service:
    image: malakasadeep/fds-user-service:latest
    container_name: user-service
    ports:
      - "5001:5001"
    environment:
      - PORT=5001
      - MONGO_URL=mongodb+srv://pgmsadeep:1234@cluster0.phudmlq.mongodb.net/FoodDelevery_DB?retryWrites=true&w=majority
      - JWT_SECRET=576520617265204465764372616674732e206465766372616674732e746f70
      - NOTIFICATION_SERVICE_URL=http://notification-service:5005
    restart: unless-stopped

  restaurant-service:
    image: malakasadeep/fds-restaurent-service:latest
    container_name: restaurant-service
    ports:
      - "5002:5002"
    environment:
      - PORT=5002
      - MONGO_URL=mongodb+srv://pgmsadeep:1234@cluster0.phudmlq.mongodb.net/FoodDelevery_DB?retryWrites=true&w=majority
      - JWT_SECRET=576520617265204465764372616674732e206465766372616674732e746f70
    restart: unless-stopped

  notification-service:
    image: malakasadeep/fds-notification-service-v2:latest
    container_name: notification-service
    ports:
      - "5005:5005"
    environment:
      - PORT=5005
      - MONGO_URL=mongodb+srv://pgmsadeep:1234@cluster0.phudmlq.mongodb.net/FoodDelevery_DB?retryWrites=true&w=majority
      - JWT_SECRET=576520617265204465764372616674732e206465766372616674732e746f70
      - EMAIL_SERVICE=gmail
      - EMAIL_USER=sadeepmalaka2@gmail.com
      - EMAIL_PASSWORD=bfxr wzmt jalb grxp
      - SMS_API_KEY=d97962ed12ebccd0870087ab1b3fc066-e50be66a-ad92-4cf5-9747-b77f9d89e1b2
    restart: unless-stopped

  order-service:
    image: malakasadeep/fds-order-service-v2:latest
    container_name: order-service
    ports:
      - "5003:5003"
    environment:
      - PORT=5003
      - MONGODB_URL=mongodb+srv://dewnijayasuriya123:event123@cluster0.r3uz9qa.mongodb.net/food_ordering_system?retryWrites=true&w=majority
      - STRIPE_SECRET_KEY=sk_test_51RD6tEGd3xGfzgsU9V5WTckVrBOAVFHBBatfWTDtUrQUYLPX098vDQZKNF9mOBGSzGHH0aSAi4wukOjxDJxgLsoQ00zD6FdivY
    restart: unless-stopped

  api-gateway:
    image: malakasadeep/fds-gateway-v2:latest
    container_name: api-gateway
    ports:
      - "80:80"
    depends_on:
      - user-service
      - restaurant-service
      - notification-service
    restart: unless-stopped
