worker_processes auto;
events {
    worker_connections 1024;
}

http {
    upstream user_service {
        server user-service:5001;
    }

    upstream restaurant_service {
        server restaurant-service:5002;
    }

    upstream order_service {
        server order-service:5003;
    }

    upstream delivery_service {
        server delivery-service:5004;
    }

    server {
        listen 80;

        location /users/ {
            proxy_pass http://user_service/;
        }

        location /restaurants/ {
            proxy_pass http://restaurant_service/;
        }

        location /orders/ {
            proxy_pass http://order_service/;
        }

        location /delivery/ {
            proxy_pass http://delivery_service/;
        }
    }
}
