worker_processes auto;
events {
    worker_connections 1024;
}

http {
    upstream user_service {
        server user-service:5001;
    }

    upstream restaurant_service {
        server restaurant-service:5002;
    }

    upstream notification_service {
        server notification-service:5005;
    }

    upstream order_service {
        server order-service:5003;
    }

    server {
        listen 80;

        location /api/users/ {
            proxy_pass http://user_service/;
        }

        location /api/restaurants/ {
            proxy_pass http://restaurant_service/;
        }

        location /api/notification/ {
            proxy_pass http://notification_service/;
        }

        location /api/orders/ {
            proxy_pass http://order_service/;
        }
    }
}