worker_processes auto;
events {
    worker_connections 1024;
}

http {
    upstream user_service {
        server user-service:5001;
    }
    
    upstream restaurant_service {
        server restaurant-service:5002;
    }
    
    upstream notification_service {
        server notification-service:5005;
    }

    upstream delivery_service {
        server delivery-service:8090;
    }
    
    server {
        listen 80;

        location /health {
            access_log off;
            add_header Content-Type application/json;
            return 200 '{"status":"ok","service":"api-gateway"}';
        }

        location /api/users/ {
            proxy_pass http://user_service/;
        }

        location /api/restaurants/ {
            proxy_pass http://restaurant_service/;
        }

        location /api/notification/ {
            proxy_pass http://notification_service/;
        }

        location /api/delivery/ {
            proxy_pass http://delivery_service/api/delivery/;
        }

        location /api/delivery-requests/ {
            proxy_pass http://delivery_service/api/delivery-requests/;
        }
        
    }
}