apiVersion: v1
kind: Secret
metadata:
  name: email-sms-secrets
  namespace: food-delivery-system
type: Opaque
stringData:
  email-service: "gmail"
  email-user: "sadeepmalaka2@gmail.com"
  email-password: "bfxr wzmt jalb grxp"
  sms-api-key: "d97962ed12ebccd0870087ab1b3fc066-e50be66a-ad92-4cf5-9747-b77f9d89e1b2"
---
apiVersion: v1
kind: Secret
metadata:
  name: stripe-secrets
  namespace: food-delivery-system
type: Opaque
stringData:
  stripe-secret-key: "sk_test_51RD6tEGd3xGfzgsU9V5WTckVrBOAVFHBBatfWTDtUrQUYLPX098vDQZKNF9mOBGSzGHH0aSAi4wukOjxDJxgLsoQ00zD6FdivY"
